### ISSUE TITLE
2 `ImportError`s:  `No module named watchdog.events`; `No module named dealer.git`

### ISSUE THREAD

**Issue by SamuelMarks** [regisb/openedx-install#15]
Wrote up [a Fabric implementation of this repo](https://github.com/offscale/offregister-openedx/blob/master/offregister_openedx/ubuntu/__init__.py), found a couple of missing dependencies, but then ran into these:

```
Warning: sudo() received nonzero return code 2 while executing 'nodeenv -p'!

[ip_addr] out: No python virtualenv is available
[ip_addr] out: 

[ip_addr] sudo: paver install_prereqs

[ip_addr] out: Traceback (most recent call last):
Warning: sudo() received nonzero return code 1 while executing 'paver install_prereqs'!

[ip_addr] out:   File "/opt/openedx/venv/bin/paver", line 11, in <module>
[ip_addr] out:     sys.exit(main())
[ip_addr] out:   File "/opt/openedx/venv/local/lib/python2.7/site-packages/paver/tasks.py", line 878, in main
[ip_addr] out:     _launch_pavement(args)
[ip_addr] out:   File "/opt/openedx/venv/local/lib/python2.7/site-packages/paver/tasks.py", line 846, in _launch_pavement
[ip_addr] out:     exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
[ip_addr] out:   File "pavement.py", line 14, in <module>
[ip_addr] out:     from pavelib import *
[ip_addr] out:   File "pavelib/__init__.py", line 4, in <module>
[ip_addr] out:     from . import assets, servers, docs, prereqs, quality, tests, js_test, i18n, bok_choy, acceptance_test
[ip_addr] out:   File "pavelib/assets.py", line 17, in <module>
[ip_addr] out:     from watchdog.events import PatternMatchingEventHandler
[ip_addr] out: ImportError: No module named watchdog.events
[ip_addr] out: 
```

```
[ip_addr] out: Traceback (most recent call last):
[ip_addr] out:   File "./manage.py", line 111, in <module>
[ip_addr] out:     startup = importlib.import_module(edx_args.startup)
[ip_addr] out:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[ip_addr] out:     __import__(name)
[ip_addr] out:   File "/opt/openedx/edx-platform/lms/startup.py", line 11, in <module>
[ip_addr] out:     settings.INSTALLED_APPS  # pylint: disable=pointless-statement
[ip_addr] out:   File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
[ip_addr] out:     self._setup(name)
[ip_addr] out:   File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
[ip_addr] out:     self._wrapped = Settings(settings_module)
[ip_addr] out:   File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
[ip_addr] out:     mod = importlib.import_module(self.SETTINGS_MODULE)
[ip_addr] out:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[ip_addr] out:     __import__(name)
[ip_addr] out:   File "/opt/openedx/edx-platform/lms/envs/production.py", line 1, in <module>
[ip_addr] out:     from .aws import *
[ip_addr] out:   File "/opt/openedx/edx-platform/lms/envs/aws.py", line 27, in <module>
[ip_addr] out:     from .common import *
[ip_addr] out:   File "/opt/openedx/edx-platform/lms/envs/common.py", line 36, in <module>
[ip_addr] out:     import dealer.git
[ip_addr] out: ImportError: No module named dealer.git
```

I've found dealer in [`edx-platform/requirements/base.txt`](https://github.com/edx/edx-platform/blob/master/requirements/edx/base.txt); not sure how `paver` and `nodeenv` are meant to be installed; so I did `apt install nodeenv` and `pip install paver`.

**Comment by SamuelMarks** [comment]
Looks like I had some permissions issues, resolved.

**Comment by regisb** [comment]
I just love it when people solve their own issues :-D Thanks for the heads-up on the fabric install!
