### ISSUE TITLE
[LMS] ImportError: No module named proj.settings

### ISSUE THREAD

**Issue by SamuelMarks** [regisb/openedx-install#16]
The CMS page opens fine, but I can't seem to get the LMS working. Debugging manually, I:

```bash
/opt/openedx/edx-platform$ sudo -u edxapp /opt/openedx/venv/bin/gunicorn --name lms --bind=127.0.0.1:8000 --max-requests=1000 lms.wsgi:application
2017-12-03 02:37:00 [62545] [INFO] Starting gunicorn 0.17.4
2017-12-03 02:37:00 [62545] [ERROR] Connection in use: ('127.0.0.1', 8000)
2017-12-03 02:37:00 [62545] [ERROR] Retrying in 1 second.
2017-12-03 02:37:01 [62545] [ERROR] Connection in use: ('127.0.0.1', 8000)
2017-12-03 02:37:01 [62545] [ERROR] Retrying in 1 second.
2017-12-03 02:37:02 [62545] [INFO] Listening at: http://127.0.0.1:8000 (62545)
2017-12-03 02:37:02 [62545] [INFO] Using worker: sync
2017-12-03 02:37:02 [62674] [INFO] Booting worker with pid: 62674
2017-12-03 02:37:02 [62674] [ERROR] Exception in worker process:
```
```python
Traceback (most recent call last):
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 106, in wsgi
    self.callable = self.load()
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 27, in load
    return util.import_app(self.app_uri)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/gunicorn/util.py", line 353, in import_app
    __import__(module)
  File "/opt/openedx/edx-platform/lms/wsgi.py", line 22, in <module>
    import lms.startup as startup
  File "/opt/openedx/edx-platform/lms/startup.py", line 11, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named proj.settings
```

Running `sudo find / -type f -name '*.settings'` I couldn't find anything relevant. How am I to generate this file?

**Comment by regisb** [comment]
Hmmmm... Looks like it's trying to load a file named `settings.py` from a `proj` folder. What's the value of the `DJANGO_SETTINGS_MODULE` environment variable? I suspect you forgot to define it, as specified [here](https://github.com/regisb/openedx-install/blob/master/config/supervisor/conf.d/lms.conf#L11).

**Comment by SamuelMarks** [comment]
@regisb You are 100% right. I'm looking at the [Django docs](https://docs.djangoproject.com/en/1.11/topics/settings/)… what should I be setting that line to?

**Comment by regisb** [comment]
You should define two environment variables that indicate Django which settings files it should use. What do you use to launch your LMS and CMS? Are you testing them manually from the command line? If yes, for the LMS you should run:

```
export DJANGO_SETTINGS_MODULE=lms.envs.production
export SERVICE_VARIANT="lms"
```

Note that these variables are automatically set by supervisor if you use supervisor to launch the services along with the configuration files provided in this repo.

**Comment by SamuelMarks** [comment]
Just tried that, same error. I have `cd`'d to `/opt/openedx/edx-platform`.

```
$ ls /opt/openedx/edx-platform/{lms,cms}/envs/production.py
/opt/openedx/edx-platform/cms/envs/production.py
/opt/openedx/edx-platform/lms/envs/production.py
```

Should I be doing something different?

**Comment by regisb** [comment]
You really should not be getting an error about `proj.settings` if you correctly defined `DJANGO_SETTINGS_MODULE` and `SERVICE_VARIANT`... You did define the environment variables in the same bash session as the `gunicorn` commands, right? Also, the environment variables should be different for the CMS.

**Comment by SamuelMarks** [comment]
Whoops, my bad. Looking through my `/var/log/supervisor/lms*` logs and I found the issue.

Somehow forgot to include `mongod` rebooting in my configuration 🔢
